apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: monitoring
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: v1.11.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 5m
  # install:
  #   createNamespace: true
  values:
    installCRDs: true