apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  # image: "otel/opentelemetry-collector-contrib:0.78.0"
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
            endpoint: "0.0.0.0:3030"

    # processors:
    #   batch:

    # exporters:
    #   logging:
    #     logLevel: debug
    #   otlp:
    #     endpoint: "your-otlp-endpoint:4317"

    exporters:
      logging:
      loki:
        endpoint: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/pusht"
      prometheus:
        endpoint: "0.0.0.0:8889"

    # service:
    #   pipelines:
    #     traces:
    #       receivers: [otlp]
    #       processors: [batch]
    #       exporters: [logging, otlp]
    #     metrics:
    #       receivers: [otlp]
    #       processors: [batch]
    #       exporters: [logging, otlp]
    #     logs:
    #       receivers: [otlp]
    #       processors: [batch]
    #       exporters: [logging, otlp]
    service:
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [loki]
        traces:
          receivers: [otlp]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          exporters: [logging,prometheus]