apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: monitoring
spec:
  releaseName: opentelemetry-operator
  chart:
    spec:
      chart: opentelemetry-operator
      version: 0.60.0
      sourceRef:
        kind: HelmRepository
        name: otel-charts
        namespace: flux-system
  interval: 1m
  values:
    admissionWebhooks:
      certManager:
        enabled: true
    manager:
      collectorImage:
        repository: "otel/opentelemetry-collector-contrib"