apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      version: 15.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 5m
  values:
    alertmanager:
      enabled: false
    server:
      config:
        global:
          scrape_interval: 15s 
          evaluation_interval: 15s
        scrape_configs:
          - job_name: otel_collector
            scrape_interval: 5s
            static_configs:
              - targets: ['collector:8889']
          - job_name: 'prometheus'
            static_configs:
              - targets: [ 'localhost:9090' ]
          - job_name: 'node-exporter'
            static_configs:
              - targets: ['node-exporter:9100']