name: Encrypt GCP Secret with SOPS

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  encrypt_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
            credentials_json: '${{ secrets.GCP_SA_JSON }}'

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          version: 'latest'

      - name: Get secret from Google Cloud Secret Manager
        run: |
          echo "SECRET_VALUE=$(gcloud secrets versions access latest --secret='${{ secrets.GCP_SECRET_NAME }}' --project='${{ secrets.GCP_PROJECT_ID }}' --format='value(payload.data)')" >> $GITHUB_ENV
      
      - name: Generate secret.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq '.data.token=strenv(SECRET_VALUE)' secret-template.yaml > secret.yaml
        
      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.6.0
        with:
          version: 'latest'
        id: install

      - name: Encrypt secret with SOPS
        run: |
          sops --encrypt --gcp-kms projects/'${{ secrets.GCP_PROJECT_ID }}'/locations/global/keyRings/sops-flux/cryptoKeys/sops-key-flux --encrypted-regex '^token$' secret.yaml > clusters/demo/secret-enc.yaml
      
      - name: Update Version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add clusters/demo/secret-enc.yaml
          git commit -am "update secret"
          git push